tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "fish"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "mas"
brew "nvm"
brew "pinentry-mac"
brew "python"
brew "ranger"
brew "yarn"

cask "adoptopenjdk8"
cask "android-sdk"
cask "brave-browser"
cask "discord"
cask "emacs"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "kicad"

mas "1Password", id: 1333542190
mas "BetterSnapTool", id: 417375580
mas "Brightness Slider", id: 456624497
mas "Todoist", id: 585829637
