tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

brew "git"
brew "git-lfs"
brew "gnupg"
brew "mas"
brew "pinentry-mac"
brew "python"
brew "nvm"
brew "yarn"
brew "nvim"

cask "iterm2"
cask "karabiner-elements"
cask "google-chrome"
cask "emacs"

brew "denisidoro/tools/navi"
brew "isacikgoz/gitin/gitin"
cask "adoptopenjdk8"
cask "android-sdk"
cask "font-jetbrains-mono"

mas "1Password", id: 1333542190
mas "BetterSnapTool", id: 417375580
mas "Todoist", id: 585829637
mas "Brightness Slider", id: 456624497 

