[user]
name = "Martin Jakubik"
email = "martindzejky@gmail.com"

[signing]
behavior = "own"
backend = "gpg"

[ui]
editor = "nvim"
pager = "delta"
diff-formatter = ":git"

[delta]
navigate = true
features = "side-by-side line-numbers decorations"

