" https://github.com/changemewtf/no_plugins
" enter the current millenium
set nocompatible

" enable syntax and plugins
syntax enable
filetype plugin on

" file autocomplete with subfolders
set path+=**
set wildmenu

" tweaks for the file browser
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" the following settings are copied from somewhere and
" are the default "sane" things to have in vimrc
" (I guess)

" general
set backspace=indent,eol,start
set linebreak
set number
set ruler
set showmatch
set textwidth=100
set undolevels=1000
set visualbell
 
" search
set hlsearch
set ignorecase
set incsearch
set smartcase
 
" indentation
set autoindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4

" colors
colorscheme solarized

" disable q: and Q because I always press them
" by mistake and I never actually use them
map q: <Nop>
nnoremap Q <nop>

" automatically switch between light and dark theme based on
" iTerm's theme (which is in turn based on OS)
if $ITERM_PROFILE == "Dark"
    set background=dark
else
    set background=light
endif

