# GIT ALIASES
# Moved from .gitconfig to get rid of that
# one unnecessary space key in 'g sw'. .gitconfig
# is now cleaner and I save a few key presses.
#
# Also, there are some additional git shortcuts in
# fish/functions that use some additional logic.

alias ga      "git add"
alias gaa     "git add --all"
alias gaaco   "git add --all && git commit"
alias gaacoa  "git add --all && git commit --amend --no-edit"
alias gaacoae "git add --all && git commit --amend"
alias gaacof  "git add --all && git commit --fixup"
alias gaacos  "git add --all && git commit --squash"
alias gb      "git branch"
alias gbl     "git blame"
alias gbm     "git branch --move"
alias gbs     "git bisect"
alias gbsb    "git bisect bad"
alias gbsg    "git bisect good"
alias gbsl    "git bisect log"
alias gbss    "git bisect start"
alias gbsv    "git bisect view"
alias gcl     "git clone"
alias gco     "git commit"
alias gcoa    "git commit --amend --no-edit"
alias gcoae   "git commit --amend"
alias gcof    "git commit --fixup"
alias gcos    "git commit --squash"
alias gcp     "git cherry-pick"
alias gcpa    "git cherry-pick --abort"
alias gcpc    "git cherry-pick --continue"
alias gcps    "git cherry-pick --skip"
alias gd      "git diff"
alias gde     "git describe --tags"
alias gds     "git diff --staged"
alias gdw     "git diff --word-diff --color-words"
alias gf      "git fetch --prune"
alias gfpl    "git fetch --prune && git pull"
alias gm      "git merge"
alias gma     "git switch master"
alias gmff    "git merge --ff-only"
alias gmnff   "git merge --no-ff"
alias gpl     "git pull"
alias gplr    "git pull --rebase"
alias gps     "git push --follow-tags"
alias gpsf    "git push --follow-tags --force-with-lease"
alias gpsu    "git push --follow-tags --set-upstream"
alias grb     "git rebase"
alias grba    "git rebase --abort"
alias grbc    "git rebase --continue"
alias grbi    "git rebase --interactive"
alias grbima  "git rebase --interactive master"
alias grbma   "git rebase master"
alias gre     "git restore"
alias gres    "git restore --staged"
alias grs     "git reset"
alias grsh    "git reset --hard"
alias grss    "git reset --soft"
alias gs      "git status"
alias gst     "git stash"
alias gstp    "git stash pop"
alias gsu     "git submodule"
alias gsua    "git submodule add"
alias gsuui   "git submodule update --init --recursive"
alias gsuur   "git submodule update --remote"
alias gswc    "git switch --create"
alias gswd    "git switch --detach"
alias gt      "git tag"
alias gts     "git tag --sign"
